ruby   '2.1.2'
source 'https://rubygems.org'

gem 'hoodoo', :git     => 'git@github.com:LoyaltyNZ/hoodoo.git',
                 :branch  => 'master'

gem 'activesupport', '~> 4.1', :require => 'active_support'
gem 'json-schema',   '~> 2.4'
