language: ruby
rvm:
  - 2.1.6

# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
#
sudo: false

# http://docs.travis-ci.com/user/caching/
#
cache: bundler

addons:
  postgresql: "9.3"

script:
  - TZ=Pacific/Auckland DATABASE_USER=postgres bundle exec rspec spec --backtrace

# https://docs.travis-ci.com/user/deployment/rubygems
# API key is encrypted and secure.
#
deploy:
  provider: rubygems
  api_key:
    secure: "LZecb7XtIICln+yH6xa2MRRfdH2G16HW+LjiV23o+a/C9/P3XXinDFGrx6Tg8VXVqe8VpRpAQbbt5l/BAOIRn332LvhuAMs+hI1T/qS59P5y3WvIebKBEUsvrPI3KLRUWqZ1QsC4rj728hsqVrBd6RtQkEA6Eph/C7WfxPqYzV4iuimyPDpghdiQ/8ZfFibD50E3R6lr/IFZsirF1XwQRwNqgwS8CZFWIoIvMpEUQGdhrmUFtynQV5edWhgQoXVadvkd+hse4TEYhyD5lsh4Ad65oBHdvR2veSgm3yHnKSmcihPAm3A/QaxvbjoVNfHK1XlKHeBhBvBuexXt9juw8DR3xPZBHt0CF+v+V4FWt0KzCIBKp/4saL+s3mBO2HtrDsrGaTuVi1YXeJdLTCNvjwDbrhEbwJ8/EgiABE1c8+63q86s5ecwhq7VZcexEbQEMafmfTX0nq79T79e6jf6RFwn+rPvDWdfUlDd0IJvgxkTx1pMsUK/gWToaMSqH92L9yt1WyKeVQmPiDLT31YnYmKO4kpHJXVc3DHRWs8LYN6flvRagBP8cwe8gkmHdZFwZZXrvdSqdjwq679X/jaXzrQGfrTHpdc8rLAz7U+RNEROERpinYb6RVKBkwT6zD3mQVQ1EwEGk6JH71TtoxPXvbAHVDg9YKOxhzqhTx97jjs="
  gem: hoodoo
  on:
    tags: true
    repo: LoyaltyNZ/hoodoo
