language: ruby
rvm:
  - 2.1.6

# http://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
#
sudo: false

# http://docs.travis-ci.com/user/caching/
#
language: ruby
cache: bundler

addons:
  postgresql: "9.3"

script:
  - TZ=Pacific/Auckland DATABASE_USER=postgres bundle exec rspec spec --backtrace

# https://docs.travis-ci.com/user/deployment/rubygems
# API key is encrypted and secure.
#
deploy:
  provider: rubygems
  api_key:
    secure: dw06uLFoYeLxXh/3efXELTcZeTGKO1Jq6X19KSn/6R2hJhlhwvHPSHIg8cQEOGr4cup7PbBlWBoUkAmwPUZLn240Y3pJ5NlGaaAb/PWiAPpE9R5MM76oAJs+yJhPTSd/9C2eo/s5saOv8MzGMPfm72nH4SWSI8vRHAZaN9RYNw9NVR1wlNO/+aEfeJVZGsGiYbZhdr+aAQ+OEgFgY7zNet0kbyq7qNPUzVB/JPsQuJvDuII6lTxe0yBVI+Jv02BeJVJw6/TKh7smZUdzfRHa5IItuPWT6/tG47JzWcb4dTYE6pSs4si33ya+yvBZ2zcRNLg/HmZl8ZwPBdtQ1Z7xbhKpZipe9GQmlLAOqESHZmuKMIVFruGZ4cMaYJoSkbpZ3vOHU50UYD4gAP874STqsVhLGk/SRG0v91Nafn/elO5aYdrPROFi8FVWoEWgXw72twxibLx1Y54K1T4f6VWESHsgvTRISei5RAwojiaCY7U/zqvMjscbXjWbpIg49ZK9gp23FW0PfEYC5OfeIs9BUDfI4L3/pinSVCqBz1RXYZhmKr78fv4RTG2XGd2wyWvZ3wjmwtPpY2ycO5RuN3I5dsai8w0Ogoae8ZjMV/zFu1ZFfY+tStQGjG3P/pg0tF70gW+dI8lCSlsrTO1t/d/PwwsZd6b/Tt/2HiWaqjsw+jQ=
  gem: hoodoo
  on:
    tags: true
    repo: LoyaltyNZ/hoodoo
